ver 51

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -41,17 +41,15 @@ jobs:
 #                name: allure-report
 #                path: target/allure-report
 
-#      - name: Check generated files
-#        run: ls -l target/
-      - name: Check if Allure Report is generated
-        run: |
-          if [ ! -d "target/allure-report" ]; then
-            echo "Allure Report not found!"
-            exit 1
-          fi
+      - name: Check generated files
+        run: ls -l target/
 
-      - name: Archive Allure Report
-        run: tar -czf allure-report.tar.gz target/allure-report
+#      - name: Check if Allure Report is generated
+#        run: |
+#          if [ ! -d "target/allure-report" ]; then
+#            echo "Allure Report not found!"
+#            exit 1
+#          fi
 
       - name: Upload Allure Report
         uses: actions/upload-artifact@v3
@@ -68,9 +66,6 @@ jobs:
         uses: actions/download-artifact@v3
         with:
           name: allure-report
-
-      - name: Unpack Allure Report
-        run: tar -xzf allure-report.tar.gz
 
       - name: Deploy Allure Report
         uses: peaceiris/actions-gh-pages@v3
